### PR TITLE
CakePHP 4.x Interface declarations

### PR DESCRIPTION
**Pull request by mikeweb85**
method and type updates to comply with CakePHP 4.x  BasePlugin, ConnectionInterface, and ReepositoryInterface

### CODE REVIEW

**Comment by markstory** [comment]
Looking good. The tests and phpcs builds are failing though.

**Comment by mikeweb85** [comment]
They were showing as failing on the 4.x-updates branch I came off of. Didn't dig very far into, yet.

**Comment by dakota** [comment]
Any more updates on this? @mikeweb85 I can take a look if you haven't had time yet.

**Comment by mikeweb85** [comment]
unfortunately I haven't had the time, and probably wont for a few more days. If you have the time, I would appreciate the eyes. From what I could tell at quick glance, the build started failing in the 4.x branch this all was then branched and forked from.

**Comment by mikeweb85** [comment]
well... out out morbid curiosity I found 2 things:  
1) for the test cases the Connection::getIndex() function was removed from the base 4.x branch. (re-added)
2) main issue is "Declaration of Cake\TestSuite\TestCase::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void" to cause the tests to fail

**Comment by markstory** [comment]
> main issue is "Declaration of Cake\TestSuite\TestCase::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void" to cause the tests to fail

This should be fixed now.

**Comment by saeideng** [comment]
which branch is correct base branch  `cake-4.x` or `cake-4.x-updates` ?

**Comment by othercorey** [comment]
I changed the target branch for this PR because the `cake-4.x-updates` branch was actually for a separate PR.

**Comment by markstory** [comment]
Merging this so I can continue fixing compatibility for Cake 4.

**Pull request merged**
