### PR TITLE
Support nested validation errors on nonexistent entities

### PR DESCRIPTION
**Pull request by josbeir**
Tests will fail because of an issue in Cake core that needs to be resolved first so **do not merge** this one just yet. 

Refs https://github.com/cakephp/cakephp/pull/12250

### CODE REVIEW

**Comment by josbeir** [comment]
Fixed in https://github.com/cakephp/cakephp/pull/12268 
Waiting for official release

**Comment by josbeir** [comment]
Closing in favour of #176

**Comment by josbeir** [comment]
This can be merged now as cake 3.6.6 is released

**Comment by lorenzo** [comment]
Thanks!

**Pull request merged**
