### PR TITLE
Run CakePHP CS

### PR DESCRIPTION
**Pull request by bcrowe**

### CODE REVIEW

**Comment by markstory** [comment]
Should we run phpcs 3 times? Seems redundant.

**Comment by bcrowe** [comment]
Gah. Sorry. Travis wasn't starting builds earlier and I was just trying to poke it. Of course we don't wanna run phpcs 3 times. :laughing:

**Comment by lorenzo** [comment]
@bcrowe can you add this in a separate build like the main cake repo has?

**Comment by bcrowe** [comment]
Ping. This should be :ok_hand: now.

**Pull request merged**
