### PR TITLE
Update dep to work on php7

### PR DESCRIPTION
**Pull request by jadb**

### CODE REVIEW

**Comment by markstory** [comment]
Php7 build is still failing :)

**Comment by jadb** [comment]
hmm, this looking more complicated than I first anticipated. @markstory could you peak at the failure and maybe point me into the right direction? Not an ES pro here...

**Comment by markstory** [comment]
It looks like one of the classnames conflicts with the new scalar type hints added in php7. I can take a look when I geto a real computer.

**Comment by jadb** [comment]
Ya - the `Bool` classname but I changed that - something else is failing... Am sure you'll figure it out much quicker than me once you are on the computer ;)

**Comment by lorenzo** [comment]
Thanks!

**Pull request merged**
