### PR TITLE
Add method for getting elastica query object

### PR DESCRIPTION
**Pull request by ankr**
Possible to get a hold on the elastica query object without compiling it.

### CODE REVIEW

**Comment by ankr** [comment]
I believe the failing tests were already failing befor this PR.

**Comment by lorenzo** [comment]
I think the method you are looking for is `compileQuery()`

**Comment by ankr** [comment]
@lorenzo In my specific case I would like to get it before it's compiled. I'm passing the returned value to `Cake\ElasticSearch\Query::setFullQuery()` after wrapping it in a `HasParent` query.

**Comment by lorenzo** [comment]
you can get the compiled one, wrap it and set it again

**Comment by ankr** [comment]
Actually no, this isn't going to work. If I use the result from `compileQuery` in a `hasParent` my filters will be applied to parent documents, and not my current `Type`.

**Comment by lorenzo** [comment]
@ankr a problem with this PR is that the `_elasticaQuery` object is empty until you call `compileQuery`

**Comment by ankr** [comment]
Gonna close this PR as I managed to resolve my issue without this method.
I still think it could could be useful being able to access the Elastica query without compiling it. But let's burn that bridge when we get to it.

**Pull request closed without merging**
