### PR TITLE
Add default conventional event mappings.

### PR DESCRIPTION
**Pull request by markstory**
This lets the elasticsearch plugin work more like the ORM.

Refs #84

### CODE REVIEW

**Comment by lorenzo** [comment]
I'm not sure that having  `Model.` is the best idea. Globally attached listeners will need to do extra work

**Comment by jippi** [comment]
`Elastic.` ?

**Comment by dario86** [comment]
I've tried this `Type.php` version, but same problem: beforeMarshal and beforeSave not called

**Comment by markstory** [comment]
@lorenzo I went with Model as the events emitted by the various traits also use `Model.`

**Comment by lorenzo** [comment]
@markstory Fair enough

**Pull request merged**
